module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/FzISXdO9Z416SQ9hVTcdB5?mode=hqrt2',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: ' https://files.catbox.moe/qg5i86.jpeg',
    NEWSLETTER_JID: '120363424614849000@g.us',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'GLITCH PHANTOMS v1',
    OWNER_NAME: 'GPT CHATU& ZANTA',
    OWNER_NUMBER: '94741336839',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: 'POWERD BY GPT TEAM',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbC8pzsICVfoGwRmpu3x',
};
